services:
  server:
    build:
      context: ./server
    ports:
      - "8081:8081"
      - "5555:5555"
    volumes:
      - ./server/uploads:/server/uploads # 掛載 uploads
    env_file:
      - ./server/.env
    depends_on:
      - db
    restart: always

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server
    restart: always

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: forumdb
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
