services:
  server:
    build:
      context: ./server
    ports:
      - "8081:8081"
      - "5555:5555"
    volumes:
      - ./server:/server # 掛載整個專案，包含 uploads 資料夾
      - /server/node_modules # 避免主機蓋掉 container 的 node_modules
    env_file:
      - ./server/.env
    depends_on:
      - db
    restart: always

  # client:
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./client/.env
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:3000/api
  #   depends_on:
  #     - server
  #   restart: always

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: forumdb
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: 123456Qsxesz
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
